version: "3"

services:
    gunicorn_web:
        build: .
        container_name: gunicorn_web
        ports:
            - 5001:5001
        volumes:
            - ../:/var/www/html/
        restart: always
